import { NgModule } from '@angular/core';
import { BrowserModule } from '@angular/platform-browser';

import { AppRoutingModule } from './app-routing.module';
import { AppComponent } from './app.component';
import { DashboardLayoutComponent } from './layout/dashboard-layout/dashboard-layout.component';
import { SharedModule } from './shared/shared.module';

import { HttpClientModule } from '@angular/common/http';
import { provideCharts, withDefaultRegisterables } from 'ng2-charts';


import {
  LucideAngularModule,
  Menu,
  Package,
  Users,
  Settings,
  User,
  ShoppingBasket,
  List,
  House,
  ClipboardList,
  Plus,
  Search,
  Pencil,
  Trash2,
  ChevronLeft,
  ChevronRight,
  Trash,
  Filter,
  ExpandIcon,
  ChevronDown,
  ChevronUp,
  X,
  LogOut,
  Mail,
  Phone,
  MapPin,
  Lock,
  Eye,
  EyeOff,
  CalendarDays,
  CreditCard,
  AtSign,
  Briefcase,
  Layers,
  KeyRound,
  LockKeyhole,
  UserPlus,
  UserCheck,
  UserPen,
  ContactRound,
  CircleUserRound,
  CheckCircle2,
  Circle,
  XCircle,
  LoaderCircle,
  Badge,
  UsersRound,
  ShieldCheck,
  BadgeCheck,
  ShoppingCart,
  LogIn,
  CircleAlert,
  AlertCircle,
  CheckCircle,
} from 'lucide-angular';

@NgModule({
  declarations: [
    AppComponent,
    DashboardLayoutComponent,
  ],
  imports: [
    BrowserModule,
    AppRoutingModule,
    SharedModule,
    HttpClientModule,
    LucideAngularModule.pick(
      {
        Menu,
        Package,
        Users,
        User,
        Settings,
        ShoppingBasket,
        List,
        House,
        ClipboardList,
        Plus,
        Search,
        Pencil,
        Trash2,
        ChevronLeft,
        ChevronRight,
        Trash,
        Filter,
        ExpandIcon,
        ChevronDown,
        ChevronUp,
        X,
        LogOut,
        Mail, 
        Phone, 
        MapPin, 
        Lock, 
        Eye, 
        EyeOff, 
        CalendarDays, 
        CreditCard,
        AtSign, 
        Briefcase, 
        Layers, 
        KeyRound, 
        LockKeyhole, 
        UserPlus,
        UserCheck, 
        UserPen, 
        ContactRound, 
        CircleUserRound, 
        CheckCircle2,
        Circle, 
        XCircle, 
        LoaderCircle, 
        Badge, 
        UsersRound, 
        ShieldCheck, 
        BadgeCheck,
        ShoppingCart,
        LogIn,
        CircleAlert,
        AlertCircle,
        CheckCircle
      }),
  ],
  providers: [
    provideCharts(withDefaultRegisterables())
  ],
  bootstrap: [AppComponent]
})
export class AppModule { }